# Generated by Django 5.0.3 on 2024-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Classe A', 'classe A'), ('Classe B', 'classe B'), ('Classe C', 'classe C'), ('Classe VIP', 'VIP')], max_length=150)),
                ('prix_enfant', models.FloatField(default=0.0)),
                ('prix_adulte', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Logo')),
                ('date_ajout', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_heure_arrivee', models.DateTimeField()),
                ('date_heure_depart', models.DateTimeField()),
                ('tarif_supplementaire_adulte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarif_supplementaire_enfant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frais_supplementaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
