# Generated by Django 5.0.3 on 2024-05-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='image',
        ),
    ]
