# Generated by Django 5.0.3 on 2024-06-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_configuration_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
