# Generated by Django 5.0.3 on 2024-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_categories_configuration_delete_pricingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_heure_arrivee', models.DateTimeField()),
                ('date_heure_depart', models.DateTimeField()),
                ('tarif_supplementaire_adulte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarif_supplementaire_enfant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frais_supplementaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
