# Generated by Django 4.2.2 on 2023-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('fonction', models.CharField(choices=[('receptionniste', 'Réceptionniste'), ('menagere', 'Ménagère'), ('caissiere', 'Caissier(e)'), ('responsable', 'Responsable'), ('stagiaire', 'Stagiaire'), ('autre', 'Autre')], max_length=100)),
                ('date_inscription', models.DateField(null=True)),
                ('date_expiration', models.DateField(null=True)),
            ],
        ),
    ]
