# Generated by Django 5.0.3 on 2024-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_secondaryuser_delete_personnel_alter_users_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secondaryuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
