# Generated by Django 5.0.3 on 2024-06-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_secondaryuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='username',
        ),
        migrations.AddField(
            model_name='secondaryuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
