# Generated by Django 5.0.3 on 2024-06-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_secondaryuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secondaryuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='secondaryuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
