# Generated by Django 5.0.3 on 2024-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_secondaryuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryuser',
            name='password',
        ),
        migrations.AddField(
            model_name='secondaryuser',
            name='hashed_password',
            field=models.CharField(default=0, max_length=128, verbose_name='hashed_password'),
            preserve_default=False,
        ),
    ]
