# Generated by Django 5.0.3 on 2024-06-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_secondaryuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryuser',
            name='nom',
            field=models.CharField(default=0, max_length=100, verbose_name='nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondaryuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='secondaryuser',
            name='prenom',
            field=models.CharField(default='Hello', max_length=100, verbose_name='prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secondaryuser',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='hashed password'),
        ),
    ]
