# Generated by Django 5.0.3 on 2024-06-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_secondaryuser_nom_secondaryuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryuser',
            name='password',
        ),
    ]
