# Generated by Django 5.0.6 on 2024-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_secondaryuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
