# Generated by Django 5.0.3 on 2024-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.IntegerField(default=0)),
                ('type_chambre', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double')], max_length=10, null=True)),
                ('etat', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée')], max_length=10)),
                ('statut', models.CharField(choices=[('sale', 'Sale'), ('propre', 'Propre')], max_length=10, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
