# Generated by Django 4.2.2 on 2023-07-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero_chambre',
            field=models.IntegerField(default=0),
        ),
    ]
