# Generated by Django 5.0.3 on 2024-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typechambre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
