# Generated by Django 4.2.2 on 2024-01-22 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambre', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to=settings.AUTH_USER_MODEL),
        ),
    ]
