# Generated by Django 4.2.2 on 2023-07-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_configuration_date_ajout'),
        ('chambre', '0002_alter_chambre_date_alter_chambre_numero_chambre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.categories'),
        ),
    ]
