# Generated by Django 4.2.2 on 2023-07-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0003_chambre_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='prix',
        ),
    ]
