# Generated by Django 4.2.2 on 2023-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0004_remove_chambre_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='categorie',
        ),
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
