# Generated by Django 4.2.2 on 2023-09-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0005_remove_chambre_categorie_chambre_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
