# Generated by Django 5.0.6 on 2024-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autrerevenucout',
            name='temps',
        ),
        migrations.AlterField(
            model_name='autrerevenucout',
            name='type',
            field=models.CharField(blank=True, choices=[('coût', 'Coût'), ('revenu', 'Revenu')], help_text='Choisissez entre Coût ou Revenu', max_length=100, null=True),
        ),
    ]
