# Generated by Django 4.2.2 on 2023-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_menu', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Boisson', 'Boisson'), ('Plat Traditionnel', 'Plat Traditionnel'), ('Plat Etranger', 'Plat Etranger')], max_length=100)),
                ('quantite', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resto')),
                ('prix', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
