# Generated by Django 5.0.6 on 2024-08-24 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_userinvoicecounter'),
        ('resto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_total', models.FloatField(default=0.0)),
                ('annulee', models.BooleanField(default=False)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.restaurant')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
