# Generated by Django 5.0.3 on 2024-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_restaurant_proprietaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='prix',
            new_name='prix_origine',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='date',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='prix_vente',
            field=models.FloatField(default=0.0),
        ),
    ]
