# Generated by Django 4.2.2 on 2024-01-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=150)),
                ('adresse_client', models.CharField(max_length=100)),
                ('date_reservation', models.DateField(auto_now=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('nombre_jours', models.IntegerField(null=True)),
                ('statut', models.CharField(choices=[('reservée', 'Reservée'), ('confirmée', 'Confirmée'), ('terminée', 'Terminée')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=150)),
                ('adresse_client', models.CharField(max_length=100)),
                ('date_reservation', models.DateField(null=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('nombre_jours', models.IntegerField(null=True)),
                ('statut', models.CharField(choices=[('reservée', 'Reservée'), ('confirmée', 'Confirmée'), ('terminée', 'Terminée')], max_length=10, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre')),
            ],
        ),
    ]
