# Generated by Django 5.0.3 on 2024-05-28 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=150)),
                ('date_reservation', models.DateField(null=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('paiement_anticipe', models.FloatField(max_length=100)),
                ('adresse_client', models.FloatField(default=0, max_length=100)),
                ('adulte_suplementaire', models.IntegerField(null=True)),
                ('enfant_suplementaire', models.IntegerField(null=True)),
                ('statut', models.CharField(choices=[('reservée', 'Reservée'), ('confirmée', 'Confirmée'), ('terminée', 'Terminée')], max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=150)),
                ('date_arrivee', models.DateField(null=True)),
                ('date_depart', models.DateField(null=True)),
                ('adulte_suplementaire', models.IntegerField(null=True)),
                ('enfant_suplementaire', models.IntegerField(null=True)),
                ('paiement_anticipe', models.FloatField(default=0, max_length=100)),
                ('frais_suplementaire', models.FloatField(default=0, max_length=100)),
                ('statut', models.CharField(choices=[('reservée', 'Reservée'), ('confirmée', 'Confirmée'), ('terminée', 'Terminée')], max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
