# Generated by Django 4.2.2 on 2023-07-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0003_chambre_categorie'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre'),
        ),
    ]
