# Generated by Django 4.2.2 on 2023-09-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquereservation',
            name='statut',
            field=models.CharField(choices=[('reservé', 'Reservé'), ('confirmé', 'Confirmé')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('reservé', 'Reservé'), ('confirmé', 'Confirmé')], max_length=10, null=True),
        ),
    ]
