# Generated by Django 5.0.3 on 2024-06-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquereservation',
            old_name='date_reservation',
            new_name='date_depart',
        ),
        migrations.RenameField(
            model_name='historiquereservation',
            old_name='adresse_client',
            new_name='frais_suplementaire',
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
