# Generated by Django 4.2.2 on 2023-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_chambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='chambre',
            field=models.CharField(max_length=10),
        ),
    ]
