# Generated by Django 5.0.3 on 2024-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_date_reservation_historiquereservation_date_depart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquereservation',
            options={'verbose_name': 'Historique de Réservation', 'verbose_name_plural': 'Historiques de Réservation'},
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0),
        ),
    ]
