# Generated by Django 4.2.2 on 2023-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_historiquereservation_statut_reservation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(null=True),
        ),
    ]
