# Generated by Django 5.0.3 on 2024-06-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_historiquereservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquereservation',
            options={},
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
