# Generated by Django 4.2.2 on 2023-08-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0005_remove_chambre_categorie_chambre_prix'),
        ('reservation', '0004_historiquereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquereservation',
            name='chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre'),
        ),
    ]
