# Generated by Django 5.0.3 on 2024-06-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_historiquereservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquereservation',
            options={'verbose_name': 'Historique de Réservation', 'verbose_name_plural': 'Historiques de Réservation'},
        ),
        migrations.AddField(
            model_name='historiquereservation',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historiquereservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='frais_suplementaire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paiement_anticipe',
            field=models.FloatField(default=0),
        ),
    ]
