# Generated by Django 4.2.2 on 2023-12-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_date_reservation'),
        ('reservation', '0005_alter_historiquereservation_chambre'),
    ]

    operations = [
    ]
