# Generated by Django 5.0.6 on 2024-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_userinvoicecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquereservation',
            name='remise',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historiquereservation',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remise',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
