# Generated by Django 4.2.2 on 2023-12-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0006_alter_chambre_prix'),
        ('reservation', '0006_merge_20231210_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquereservation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambre.chambre'),
        ),
    ]
