# Generated by Django 4.2.2 on 2023-09-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
